# Generated by Django 4.0.3 on 2022-04-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.localuser'),
        ),
    ]
